---
icingaweb2_db:
  type: mysql
  name: icingaweb2
  host: 127.0.0.1
  user: poweruser
  password: poweruser
icingaweb2_db_import_schema: true
icingaweb2_resources:
  icingadb:
    type: db
    db: mysql
    host: localhost
    dbname: icingadb
    username: poweruser
    password: poweruser
    use_ssl: 0
    charset: utf8
  director:
    type: db
    db: mysql
    host: localhost
    dbname: director
    username: poweruser
    password: poweruser
    use_ssl: 0
    charset: utf8
  x509:
    type: db
    db: mysql
    host: localhost
    dbname: x509
    username: poweruser
    password: poweruser
    use_ssl: 0
    charset: utf8
icingaweb2_modules:
  director:
    enabled: true
    source: package
    import_schema: true
    run_kickstart: false
    kickstart:
      config:
        endpoint: icinga-dev
        host: 127.0.0.1
        username: poweruser
        password: poweruser
    config:
      db:
        resource: director
  icingadb:
    enabled: true
    source: package
    commandtransports:
      instance01:
        transport: api
        host: 127.0.0.1
        username: poweruser
        password: poweruser
    config:
      icingadb:
        resource: icingadb
      redis:
        tls: '0'
    redis:
      redis1:
        host: "127.0.0.1"
        password: redis-pass
  x509:
    enabled: true
    source: package
    config:
      backend:
        resource: x509
    database:
      import_schema: true
      type: mysql
      host: localhost
      port: 3306
      user: poweruser
      password: poweruser
  businessprocess:
    enabled: true
    source: package

icingaweb2_admin_username: icinga
icingaweb2_admin_password: icinga
